var axios = require('axios');
const auth = require('./auth');

const updateShippingDetails=async () =>{
  var data = JSON.stringify({
    "order_id": order_id, // generated by shiprocket
    "shipping_customer_name": "Majin Bu",
    "shipping_phone": "9988998899",
    "shipping_address": "Earth",
    "shipping_address_2": "",
    "shipping_city": "Pune",
    "shipping_state": "Maharashtra",
    "shipping_country": "India",
    "shipping_pincode": 110077
  });


var res=(await auth.res());
console.log(res["token"]);
  var config = {
    method: 'post',
    url: 'https://apiv2.shiprocket.in/v1/external/orders/address/update',
    headers: {
      'Content-Type': 'application/json',
      'Authorization':'Bearer '+ res["token"]
    },
    data : data
  };

  axios(config)
  .then(function (response) {
    console.log(JSON.stringify(response.data));
  })
  .catch(function (error) {
    console.log(error);
  });
}
