var axios = require('axios');
const auth=require('./auth');
const generateSlip=async () =>{
  var data = JSON.stringify({
    "order_id":order_id , // generated by shiprocket
    "order_date": "2018-05-08 12:23",
    "channel_id": "27202",
    "billing_customer_name": "Jax",
    "billing_last_name": "Tank",
    "billing_address": "Dust2",
    "billing_city": "New Delhi",
    "billing_pincode": "110002",
    "billing_state": "Delhi",
    "billing_country": "India",
    "billing_email": "jax@counterstike.com",
    "billing_phone": "9988998899",
    "shipping_is_billing": true,
    "order_items": [
      {
        "name": "Delta",
        "sku": "delta123",
        "units": 10,
        "selling_price": "1000"
      }
    ],
    "payment_method": "COD",
    "sub_total": 4000,
    "length": 100,
    "breadth": 50,
    "height": 10,
    "weight": 0.5,
    "pickup_location": "HomeNew",
    "vendor_details": {
      "email": "abcdd@abcdd.com",
      "phone": 9879879879,
      "name": "Coco Cookie",
      "address": "Street 1",
      "address_2": "",
      "city": "delhi",
      "state": "new delhi",
      "country": "india",
      "pin_code": "110077",
      "pickup_location": "HomeNew"
    }
  });

var res=(await auth.res());
console.log(res["token"]);
  var config = {
    method: 'post',
    url: 'https://apiv2.shiprocket.in/v1/external/shipments/create/forward-shipment',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': 'Bearer '+ res["token"]
    },
    data : data
  };

  axios(config)
  .then(function (response) {
    console.log(JSON.stringify(response.data));
  })
  .catch(function (error) {
    console.log(error);
  });
}
