var axios = require('axios');
const auth=require("./auth");
const generateInvoice=async ()=>{
  var data = JSON.stringify({
    "ids": [
      "152469567"//order_ids generated by shiprocket
    ]
  });

let res=await auth.res();
console.log(res["token"])

  var config = {
    method: 'post',
    url: 'https://apiv2.shiprocket.in/v1/external/orders/print/invoice',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': 'Bearer '+res["token"]
    },
    data : data
  };

  axios(config)
  .then(function (response) {
    console.log(JSON.stringify(response.data));
  })
  .catch(function (error) {
    console.log(error);
  });
}
generateInvoice()
