var axios = require('axios');
const auth=require('./auth');

const generateAWB =async ()=>{
  var data = JSON.stringify({
    "shipment_id": 152017066, //shipment id generated by shiprocket
    "courier_id": "10"
  });

let res=await auth.res();
console.log(res["token"]);
  var config = {
    method: 'post',
    url: 'https://apiv2.shiprocket.in/v1/external/courier/assign/awb',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': 'Bearer '+res["token"]
    },
    data : data
  };

  axios(config)
  .then(function (response) {
    console.log(JSON.stringify(response.data));
  })
  .catch(function (error) {
    console.log(error);
  });
}
generateAWB()
